pages = Any["Home" => "index.md",
            "Introduction to Catalyst" => Any["introduction_to_catalyst/catalyst_for_new_julia_users.md",
                                              "introduction_to_catalyst/introduction_to_catalyst.md" ],
            "Catalyst Functionality" => Any["catalyst_functionality/dsl_description.md",
                                            "catalyst_functionality/programmatic_CRN_construction.md",
                                            "catalyst_functionality/compositional_modeling.md",
                                            "catalyst_functionality/constraint_equations.md",
                                            "catalyst_functionality/parametric_stoichiometry.md",
                                            "catalyst_functionality/network_analysis.md",
                                            "Model creation examples" => Any["catalyst_functionality/example_networks/basic_CRN_examples.md",
                                                                             "catalyst_functionality/example_networks/hodgkin_huxley_equation.md",
                                                                             "catalyst_functionality/example_networks/smoluchowski_coagulation_equation.md"]],
            "Catalyst Applications" => Any["catalyst_applications/simulation_structure_interfacing.md",
                                           "catalyst_applications/advanced_simulations.md",
                                           "catalyst_applications/homotopy_continuation.md",
                                           "catalyst_applications/bifurcation_diagrams.md"],
            "Inverse Problems" => Any["inverse_problems/parameter_estimation.md",
                                      "inverse_problems/petab_ode_param_fitting.md",
                                      "inverse_problems/behaviour_optimization.md"],
            "FAQs" => "faqs.md",
            "API" => "api/catalyst_api.md"]