name: "Tests"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  # Skip intermediate builds: always, but for the master branch.
  # Cancel intermediate builds: always, but for the master branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@v1"
    with:
      coverage: false
    secrets: "inherit"
